__object__:
  path: depth_anything_3.model.da3
  name: NestedDepthAnything3Net
  args: as_params

anyview:
  __inherit__: depth_anything_3.configs.da3-giant

metric:
  __inherit__: depth_anything_3.configs.da3metric-large
